[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
ffi = true
fs_permissions = [{ access = "read", path = "./script/encrypted-secret.hex" }]

[rpc_endpoints]
ritual = "https://rpc.ritualfoundation.org"

[etherscan]
ritual = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer.ritualfoundation.org/api" }
